# Site settings
title: 个人简历
description: 个人简历
favicon: /assets/img/avatar2.ico
baseurl: https://stdupanda.github.io/resumecard
url: https://stdupanda.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-85920043-1zzz
# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: 高世雄
  title: Java 工程师
  address: 北京海淀区
  email: 1197591680@qq.com
  link: https://github.com/stdupanda
  weibo: 暂无
  github: stdupanda
  #已隐藏 linkedin: 暂无
  #已隐藏 twitter: 暂无
  gavatar: /resumecard/assets/img/avatar.JPG
# stackoverflow:
# stackoverflow: 4582127
  workHistory:
    - work0:
      company: 多区域城市公交云卡系统
      location: Beijing, China
      title: Java工程师
      started: 2018
      duration: (2017.03 - Present)
      description: 1. 优化已有业务流程，按模块拆分业务逻辑，简化功能具体实现<br/><br/>2. 多区域云卡接口集成适配，对账、清算、公交系统拆分<br><br/>3. 针对高峰期业务进行系统优化，提升系统并发性能
    - work1:
      company: 气象资料业务系统
      location: Shijiazhuang, China
      title: Java工程师
      started: 2017
      duration: (2016.10 - Present)
      description: 1. 梳理已有业务流程，使用SSM替换部分老旧业务代码以加速项目开发进度，降低系统各模块的耦合，增加事务控制保证业务数据安全性，增加业务数据缓存以优化系统响应速度。<br/><br/>2. 分析大数据量业务对应的db表结构，结合业务数据量制定实施分表策略，优化数据存储并加快业务查询响应速度。<br/><br/>3. 实现气象资料年报、元数据管理中心等模块业务分析与架构设计，跟进项目组成员进度、疑难问题，保证整体功能满足用户需求并上线实现稳定运行。
    - work2:
      company: 智能设备安卓App开发
      location: Shijiazhuang, China
      title: Java工程师
      started: 2016
      duration: (2016.09)
      description: 1. 负责App整体架构设计和功能实现。<br/><br/>2. 调整后台线程策略实现通讯数据收发机制优化，优化性能降低CPU消耗10%。<br/><br/>3. 整理总结公司内部通用安卓App框架。<br/><br/>
    - work3:
      company: 温湿度设备监控系统
      location: Shijiazhuang, China
      title: Java工程师
      started: 2016
      duration: (2016.03 - 2016.09)
      description: 1. 负责项目业务分析和框架设计。<br/><br/>2. 采用tomcat集群+DBCache满足较高并发下的业务处理要求，SSM实现系统各个业务功能。<br/><br/>3. 负责移动端API接口设计、安卓App的设计、开发和测试优化工作。<br/><br/>4. 大并发量情况下调整db分表，优化实时监控功能的查询效率；采用Cache减轻mysql读取压力。
    - work4:
      company: 省级证件信息管理系统
      location: Shijiazhuang, China
      title: Java工程师
      started: 2015
      duration: (2015.04 - 2016.02)
      description: 1. 负责spring+struts+mybatis架构实现证件信息录入、多维信息查询统计与Highcharts图表展示、用户-角色-权限分级绑定，DWZ实现前台用户界面。<br/><br/>2. 负责oracle数据库维护、定时备份、用户数据按需统计导出、excel导出。
    - work5:
      company: 省级人员信息管理系统
      location: Shijiazhuang, China
      title: Java工程师
      started: 2014
      duration: (2014.10 - 2015.04)
      description: 1. 负责ssh+easyui架构实现人员信息管理、分类信息统计、按角色审核操作。<br/><br/>2. 部署RedHat到服务器并配置nginx代理静态内容，tomcat提供业务系统动态访问支持，Apache提供对公众门户网站访问支持。
    - work6:
      company: 省级投资项目管理系统
      location: Shijiazhuang, China
      title: Java工程师
      started: 2014
      duration: (2014.01 - 2014.10)
      description: 1. 根据实际需求，完成系统Oracle报表统计功能修改，百万行级数据检索统计从2分钟优化到10秒内；将原系统web容器从tomcat调整到weblogic并配置ehcache，提升系统并发数不低于600，提高系统稳定性；<br/><br/>2. 完成与国家政务内网系统webservice接口对接开发，采用spring+quartz实现定时采集Oracle数据并组织，然后调用webservice接口上传。<br/>目前系统已稳定运行一年无任何故障。3. 完成系统消息发布管理模块的设计与开发实现，完成项目信息分类统计的实现。<br/><br/>目前该系统已交付甲方运行稳定，基本不需额外投入人力维护。

  educationHistory:
    - education1:
      organization: 石家庄铁道大学
      location: Shijiazhuang, China
      degree: 本科
      major: 计算机
      started: 2010
      duration: (2010 - 2014)
      description: 所学课程包括LINUX/UNIX基础、操作系统、C语言程序设计、数据结构、编译原理、计算机算法导论、计算机网络等，受益颇深。<br/>参与基于trivium算法的能量攻击研究、某研究所通讯监控系统等项目。<br/>课程设计题目实现基于SIP协议的Android客户端。<br/>对待工作认真负责，善于沟通、协调，有较强的组织能力与团队精神；<br/>与人和善、乐观上进、有爱心愿意和他人沟通；<br/>上进心强、勤于学习能不断提高自身的能力与综合素质；<br/>积极向上，特别愿意向上争取发展空间.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Sufficient
  programmingSkills:
    - skill1:
      name: Java/Java EE
      percentage: 100%
    - skill2:
      name: Linux
      percentage: 80%
    - skill3:
      name: Javascript/Html/EasyUI/DWZ
      percentage: 70%
    - skill4:
      name: Android
      percentage: 60%
