# Site settings
title: 个人简历
description: 个人简历
favicon: /assets/img/avatar2.ico
baseurl: https://stdupanda.github.io/resumecard
url: https://stdupanda.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-85920043-1
# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: 高世雄
  title: Java 工程师
  address: 北京海淀区
  email: 1197591680@qq.com
  link: https://github.com/stdupanda
  weibo: 暂无
  github: stdupanda
  #已隐藏 linkedin: 暂无
  #已隐藏 twitter: 暂无
  gavatar: /resumecard/assets/img/avatar.JPG
# stackoverflow:
# stackoverflow: 4582127
  workHistory:
    - work1:
      company: 气象资料业务系统
      location: Shijiazhuang, China
      title: Java工程师
      started: 2017
      duration: (2016.10 - Present)
      description: 1.负责旧项目业务流程梳理，常用功能效率优化，数据库结构重新调整。<br/><br/>2.实现旧项目代码重构，调整设计进行模式优化。<br/><br/>3.按照实际业务需求进行新功能的开发.
    - work2:
      company: 智能设备安卓App开发
      location: Shijiazhuang, China
      title: Java工程师
      started: 2016
      duration: (2016.09)
      description: 1.负责App整体架构设计和功能实现。<br/><br/>2.调整并发策略实现通讯机制优化，并减轻界面性能消耗。<br/><br/>3.整理项目框架抽象出公司内部通用安卓App框架。
    - work3:
      company: 温湿度设备监控系统
      location: Shijiazhuang, China
      title: Java工程师
      started: 2016
      duration: (2016.03 - 2016.09)
      description: 1.负责项目业务分析和框架设计，tomcat集群+DBCache保证多并发下的业务处理能力。<br/><br/>2.SSM实现系统各个业务功能并测试。<br/><br/>3.负责移动端API接口设计、安卓App的设计与开发和测试工作。<br/><br/>4.大并发量情况下调整db分表，优化实时监控功能的查询效率；采用Cache减轻mysql压力。
    - work4:
      company: 省级证件信息管理系统
      location: Shijiazhuang, China
      title: Java工程师
      started: 2015
      duration: (2015.04 - 2016.02)
      description: 1.负责spring+struts+mybatis架构实现证件录入、证件信息统计、分级权限绑定，UI采用DWZ框架实现。<br/><br/>2.负责oracle数据库维护、支持用户数据统计导出、excel导出。<br/><br/>目前系统已交付甲方验收并运行稳定，除数据维护外基本无需再投入人力。
    - work5:
      company: 省级人员信息管理系统
      location: Shijiazhuang, China
      title: Java工程师
      started: 2014
      duration: (2014.10 - 2015.04)
      description: 1.负责ssh+easyui架构实现人员信息管理、分类信息统计、按角色审核操作。<br/><br/>2.负责部署RedHat服务器并配置nginx代理静态内容，tomcat提供业务系统动态访问支持，Apache提供对公众门户网站访问支持。<br/><br/>目前系统已交付甲方验收运行稳定，基本无需再投入人力维护。
    - work6:
      company: 省级投资项目管理系统
      location: Shijiazhuang, China
      title: Java工程师
      started: 2014
      duration: (2014.01 - 2014.10)
      description: 1.根据实际需求，完成系统Oracle报表统计功能修改，百万行级数据检索统计从2分钟优化到10秒内；将原系统web容器从tomcat调整到weblogic并配置ehcache，提升系统并发数不低于600，提高系统稳定性；<br/><br/>2.完成与国家政务内网系统webservice接口对接开发，采用spring+quartz实现定时采集Oracle数据并组织，然后调用webservice接口上传。目前系统已稳定运行一年无任何故障。<br/><br/>3.完成系统消息发布管理模块的设计与开发实现，完成项目信息分类统计的实现。<br/><br/>目前该系统已交付甲方运行稳定，基本不需额外投入人力维护。

  educationHistory:
    - education1:
      organization: 石家庄铁道大学
      location: Shijiazhuang, China
      degree: 本科
      major: 计算机
      started: 2010
      duration: (2010 - 2014)
      description: 所学课程包括LINUX/UNIX基础、操作系统、C语言程序设计、计算机算法导论、计算机网络等，受益颇深。<br/>参与了导师的几个项目。<br/>课程设计题目实现基于SIP协议的Android客户端。<br/>对待工作认真负责，善于沟通、协调，有较强的组织能力与团队精神；<br/>与人和善、乐观上进、有爱心愿意和他人沟通；<br/>上进心强、勤于学习能不断提高自身的能力与综合素质；<br/>积极向上，特别愿意向上争取发展空间.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Sufficient
  programmingSkills:
    - skill1:
      name: Java/Java EE
      percentage: 100%
    - skill2:
      name: Javascript
      percentage: 90%
    - skill3:
      name: Android
      percentage: 70%
    - skill4:
      name: Linux
      percentage: 70%
